# base image with just our source files
FROM mhart/alpine-node:9 as base
WORKDIR /app
COPY package.json .
RUN yarn install --production
COPY ./src ./src

# test image installs development dependencies
# and runs testing commands
FROM base as test
RUN yarn
COPY .eslintrc.json .
RUN yarn run lint
RUN yarn run test

# final production image
FROM base as prod
EXPOSE 1337
CMD ["node", "src/index.js"]
